{
    "event_type": "failure",
    "task_type": "BootstrapSpokeAsTask",
    "task_params": {
        "puppet_account_id": "371001508480",
        "account_id": "441534559121",
        "iam_role_arns": [],
        "role_name": "AWSCloudFormationStackSetExecutionRole",
        "permission_boundary": "arn:aws:iam::aws:policy/AdministratorAccess"
    },
    "params_for_results": {
        "account_id": "441534559121"
    },
    "exception_type": "<class 'botocore.exceptions.ClientError'>",
    "exception_stack_trace": [
        "Traceback (most recent call last):\n",
        "  File \"/Users/torcrane/Projects/aws-service-catalog-tools-workshop/venv/lib/python3.7/site-packages/luigi/worker.py\", line 199, in run\n    new_deps = self._run_get_new_deps()\n",
        "  File \"/Users/torcrane/Projects/aws-service-catalog-tools-workshop/venv/lib/python3.7/site-packages/luigi/worker.py\", line 141, in _run_get_new_deps\n    task_gen = self.task.run()\n",
        "  File \"/Users/torcrane/Projects/aws-service-catalog-tools-workshop/venv/lib/python3.7/site-packages/servicecatalog_puppet/workflow/management.py\", line 25, in run\n    self.puppet_account_id, iam_role_arns_to_use, self.permission_boundary,\n",
        "  File \"/Users/torcrane/Projects/aws-service-catalog-tools-workshop/venv/lib/python3.7/site-packages/servicecatalog_puppet/sdk.py\", line 132, in bootstrap_spoke_as\n    core.bootstrap_spoke_as(puppet_account_id, iam_role_arns, permission_boundary)\n",
        "  File \"/Users/torcrane/Projects/aws-service-catalog-tools-workshop/venv/lib/python3.7/site-packages/servicecatalog_puppet/core.py\", line 220, in bootstrap_spoke_as\n    \"cloudformation\", cross_accounts\n",
        "  File \"/Users/torcrane/Projects/aws-service-catalog-tools-workshop/venv/lib/python3.7/site-packages/betterboto/client.py\", line 166, in __enter__\n    RoleSessionName=role_session_name,\n",
        "  File \"/Users/torcrane/Projects/aws-service-catalog-tools-workshop/venv/lib/python3.7/site-packages/botocore/client.py\", line 316, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
        "  File \"/Users/torcrane/Projects/aws-service-catalog-tools-workshop/venv/lib/python3.7/site-packages/botocore/client.py\", line 635, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n",
        "botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::371001508480:user/torcranedev is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::441534559121:role/AWSCloudFormationStackSetExecutionRole\n"
    ]
}